# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    category_container:
        class: AppBundle\Services\CategoryContainer
        arguments: [ '@doctrine.orm.entity_manager' ]
        calls:
         - method: getCategories

    app.picture_uploader:
        class: AppBundle\Services\FileUploader
        arguments: ['%upload_dir%']